# Generated by Django 4.2.2 on 2023-07-02 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carspecs',
            options={'verbose_name_plural': 'CarSpecs'},
        ),
    ]
